### ISSUE TITLE
Players doesn't receive the HP & Mana incrementation progressively.

### ISSUE THREAD

**Issue by AxDSan** [balannarcis96/Tera_Emulator_v1xxx#1]
So just started my server and noticed few stuff that makes the game feel void and empty, I know this is not the final release, and it will have many fixes before you even release the final, however working hand by hand I think it could be a great first step in continuing development, Now this problem, in particular, is only (afaik) present in new characters, I went and started the server, loaded the game and as soon as I hit the main starter area, I noticed that my health and my mana was not full, and played around 5-9 minutes and noticed that the players doesn't receives the automated HP & Mana Incrementation, I know like I said the server is missing this feature, if you could pull this feature for future versions it will be great, however I will keep working locally to see if I can imlpement it myself, then I'll report.

**Comment by AxDSan** [comment]
Alright, first let me apologize, I just noticed I wrote 2 issues in one xD take a closer look:

1. New players don't receive full HP & Mana on creation. (on `RCreatePlayer`, when you `GetStarterStats` you initialize newPlayer->_stats.maxHp to its value, the only thing was missing is to also initialize `_currentHp` & `_currentMp` also to their respecitve values 👍 )

2. Players don't receive automatic HP & Mana Regen.

Since the first issue is already solved, I'm hunting the second issue which you said it has to do with the Abnormality-System, I will wait until you polish the systems so you can get to Abnormality and Skills 💃

**Comment by balannarcis96** [comment]
like i said allready, i have't done the Abnormality [buffs][effects] system,, that is responsibe for regeining mp/hp , etc etc, and i left the mp/hp not full for when i will start working on abnormality system , it will has something to regen.
