### ISSUE TITLE
Moving item in Inventory causes a Crash.

### ISSUE THREAD

**Issue by AxDSan** [balannarcis96/Tera_Emulator_v1xxx#2]
Still haven't been able to reproduce it since I just played it a bit and when moved the items in the inventory the game crashed, I know that this particular version is not even on final release and it should have many fixes before it happens, but I'm just reporting here what I'm seeing, like I said in the previous report, if I fix this on my own, I will comeback and report.

**Comment by balannarcis96** [comment]
I resolved!

**Comment by AxDSan** [comment]
@balannarcis96 Lovely! you're a beast! 👍 now to move onto the next areas :D
